version: '3.8'
services:
  middleware:
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - auth
      - user
      - product
      # - order
      # - payment

  auth:
    build: ../ecommerce_authenticator
    ports:
      - "8081:8081"

  user:
    build: ../ecommerce_user
    ports:
      - "8082:8082"

  product:
    build: ../ecommerce_product
    ports:
      - "8083:8083"

  # order:
  #   build: ../ecommerce_order
  #   ports:
  #     - "8084:8084"

  # payment:
  #   build: ../ecommerce_payment
  #   ports:
  #     - "8085:8085"