version: '3.8'
services:
  middleware:
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - auth
      - user
      # - product

  auth:
    build: ../authenticator
    ports:
      - "8081:8081"

  user:
    build: ../user_ms
    ports:
      - "8082:8082"

  # product:
  #   build: ../Ecommerce-Product
  #   ports:
  #     - "8083:8083"